max_seq_len: 4096
tokenizer_name: EleutherAI/gpt-neox-20b
seed: 1
precision: amp_fp16
  
models:
-
  model_name: mpt_test
  # Tokenizer
  tokenizer:
    name: ${tokenizer_name}
    kwargs:
      model_max_length: ${max_seq_len}
  model:
    name: mpt_causal_lm
    init_device: cpu
    d_model: 768
    n_heads: 12
    n_layers: 12
    expansion_ratio: 4
    max_seq_len: ${max_seq_len}
    vocab_size: 50368
    attn_config:
      attn_impl: triton

device_eval_batch_size: 4

# FSDP config for model sharding
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: FULL

# gauntlet points to tasks
icl_tasks: 'eval/yamls/tasks.yaml'
model_gauntlet: 'eval/yamls/model_gauntlet.yaml'